project:
  type: website
  output-dir: docs

website:
  title: "Andrew Garcia Leopold"
  description: "Andrew Garcia Leopold is student at CSU Northridge"
  navbar:
    left:
      - projects.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    mainfont: Georgia
    font-size: 1.2rem
    linkcolor: "#0ae5ea"
    monofont: arial
    css: styles.css
    toc: true



